### ISSUE TITLE
Issue using react native with expo

### ISSUE THREAD

**Issue by usafder** [wumke/react-native-immediate-phone-call#11]
getting this error whenever I call RNImmediatePhoneCall.immediatePhoneCall:

undefined is not an object (evaluating '_reactNative.NativeModules.RNImmediatePhoneCall.immediatePhoneCall')

**Comment by wumke** [comment]
No experience with expo myself, but the error makes me think that the native modules are not linked in the native projects.
(If I remember it right you need to do special tricks when using expo and libraries that have native modules...)

**Comment by usafder** [comment]
Is it possible that the error is occurring because I am testing it on the emulator ?

**Comment by wumke** [comment]
The emulator should find the module since it executes the same javascript bundle, if it should not work on the emulator you should get another error in the logs.

**Comment by eleallegue** [comment]
I have the same issue, I was testing with Expo Snack for seeing the library working, and I get the same error you mentioned @usafder . On the other hand, @wumke there is an easy way to link the native modules to the native projects that is writing in the command line `$ react-native link` this will do the job.
Still, the issue is not fixed and it should be working because it can work same way using Expo than Reat-native unless, for some reason, it does not work on expo-cli.

**Comment by wumke** [comment]
Can libraries that use native code use expo?
[https://docs.expo.io/versions/latest/expokit/eject/](https://docs.expo.io/versions/latest/expokit/eject/)

**Comment by eleallegue** [comment]
> "a specific Native Module which is not supported by React Native Core or the Expo SDK"

I mean, is this library not supported by ReactNative Core? I mean, it could be not supported by the Expo SDK, I'm gonna find that out, but it's weird it is not supported by react
