### ISSUE TITLE
Can not be release app with crash

### ISSUE THREAD

**Issue by NguyenPhatBG** [wumke/react-native-immediate-phone-call#23]
![capture](https://user-images.githubusercontent.com/33904172/53221124-91c54980-369a-11e9-9392-144354167454.PNG)

**Comment by wumke** [comment]
I've not seen this myself, did you already try clearing the project, build files, invalidate caches etc...? Android Studio and Xcode seem to mess up sometimes, leading to a whole range of strange issues!

**Comment by NguyenPhatBG** [comment]
I'm try with react-native version 58.4 / 58.5 on two project, It's also wrong like that, You had try new react-native version :(
Now, I'm using react-native-phone-call to instead, can you please check with new rn version !!!

**Comment by wumke** [comment]
I recently created a fresh new project with rn58 but was forced immediataly to downgrade to rn57 due to other library limits. In my experience it better not to use the latest rn version when you depend on external libs... Another good tip: commit node_modules folder in your own project repo.

If you find the reason for the error, please let me know, then I can make changes and mention which library versions to use with which rn version.

**Comment by wumke** [comment]
see https://github.com/wumke/react-native-immediate-phone-call/issues/30
