### ISSUE TITLE
Using default Phone app

### ISSUE THREAD

**Issue by edolix** [wumke/react-native-immediate-phone-call#7]
Hello, 

thanks for this repo!

When i start a new call on my phone is using Skype as default app. 

Can i use the "default" Phone app?

**Comment by wumke** [comment]
I really have no idea how to force default phone app, and if that is possible with another default app set... after all, you set another default app because you want to use it always!

If you find out how to fix, I'll be glad to hear it from you.

**Comment by edolix** [comment]
Ok, but why it open Skype? Is there a logic behind?

**Comment by wumke** [comment]
I guess because you have said once 'use allways this app' for the 'ACTION_CALL' intent? 
So it's the standard Android OS logic.

I do not have a test device at the moment, neither the time to investigate, so If you can point me in the right direction of implementing a 'force system default app' for Android I will implement it in the next update.

**Comment by edolix** [comment]
Thank you @wumke! I'll investigate on it!
